server:
  port: 8095
spring:
  application:
    name: accounts
  #local;
  datasource:
    url: jdbc:mysql://localhost:3306/bankly
    username: "{cipher}98a05d32a1c9a667ecf992e213c640eab92bdafb77a0dd8db156e3d3b092cfc0"
    password: "{cipher}98a05d32a1c9a667ecf992e213c640eab92bdafb77a0dd8db156e3d3b092cfc0"
  jpa:
    show-sql: true 

# MySQL
    hibernate: 
      ddl-auto: update
management:
  health:
    defaults:
      enabled: true
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
accounts:
  message: "Welcome to Bankly accounts related local APIs "
  contactDetails:
    name: "Landry - DIT"
    email: "landry.shema@62.163.54.21.com"
  onCallSupport:
    - (514) 641-5166
