spring:
  application:
    name: accounts
  #local;
  datasource:
    url: jdbc:mysql://localhost:3306/bankly
    username: root
    password: root
  jpa:
    show-sql: true 

# MySQL
    hibernate: 
      ddl-auto: update
management:
  health:
    defaults:
      enabled: true
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true      
accounts:
  message: "Welcome to Bankly accounts related local APIs "
  contactDetails:
    name: "Landry - Developer"
    email: "landry.shema@51.173.42.31.com"
  onCallSupport:
    - (514) 641-5166
server:
  port: 8095
