server: 
  port: 8095
spring:
  application:
    name: accounts
  datasource:
    url: jdbc:mysql://mysql-ds:3306/bankly
    username: root
    password: root
    
  jpa:
    show-sql: true 

# MySQL
    hibernate: 
      ddl-auto: update
