server:
  port: 9090
spring:
  application:
    name: broker
#-------- CLOUD CONFIGS, RABBITMQ --------------
  cloud:
    function:
      definition: accountDetails
    stream:
      bindings:
        accountDetails-in-0:
          destination: send-communication
          group: ${spring.application.name}
        accountDetails-out-0:
          destination: communications-sent

  rabbitmq:
    host: rabbitmq-service
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s
#-------- ACTUATOR & OBSERVABILITY CONFIGS --------------
management:
  endpoints:
    web:
      exposure:
        include: "*"
management:
  endpoint:
    health:
      show-details: always
management:
  tracing:
    sampling:
      probability: 1.0


